export const ADMIN_ROUTE = '/admin'
export const SHOP_ROUTE = '/'
export const CART_ROUTE = '/cart'
export const DEVICE_ROUTE = '/device'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const BASE_API_URL = 'http://localhost:5000/api'